build:
  environment:
          php: '5.6.0'

  tests:
    override:
      -
        command: 'vendor/bin/phpspec run -c ci/phpspec-with-coverage.yml'
        coverage:
          file: 'coverage.clover'
          format: 'php-clover'
      -
        command: 'vendor/bin/phpunit'
      -
        command: 'phpenv global 5.5.25 && vendor/bin/phpspec run'
      -
        command: 'phpenv global 5.5.25 vendor/bin/phpunit'
      -
        command: 'phpenv global hhvm && vendor/bin/phpspec run'
      -
        command: 'phpenv global hhvm vendor/bin/phpunit'


tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    sensiolabs_security_checker: true
    php_mess_detector:
        config:
            ruleset: ci/phpmd.xml

checks:
    php:
        code_rating: true
        duplication: true

build_failure_conditions:
    - 'issues.label("coding-style").exists'         # No coding style issues allowed
    - 'issues.severity(>= MINOR).exists'             # New issues of major or higher severity
    - 'project.metric("scrutinizer.quality", < 8)' # Code Quality Rating drops below 8.5
    - 'project.metric("scrutinizer.test_coverage", < 1)' # Code Coverage drops below 100%

filter:
    excluded_paths:
        - tests/performance/*
